/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FinanceGuard {
  export type TransactionStruct = {
    id: BigNumberish;
    user: AddressLike;
    transactionType: BigNumberish;
    description: string;
    encryptedAmount: BytesLike;
    category: string;
    timestamp: BigNumberish;
    isEncrypted: boolean;
  };

  export type TransactionStructOutput = [
    id: bigint,
    user: string,
    transactionType: bigint,
    description: string,
    encryptedAmount: string,
    category: string,
    timestamp: bigint,
    isEncrypted: boolean
  ] & {
    id: bigint;
    user: string;
    transactionType: bigint;
    description: string;
    encryptedAmount: string;
    category: string;
    timestamp: bigint;
    isEncrypted: boolean;
  };
}

export interface FinanceGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTransaction"
      | "encryptedMonthlyExpense"
      | "encryptedMonthlyIncome"
      | "getEncryptedMonthlyExpense"
      | "getEncryptedMonthlyIncome"
      | "getTransaction"
      | "getUserTransactionCount"
      | "getUserTransactions"
      | "getYearMonth"
      | "protocolId"
      | "userTransactionCount"
      | "userTransactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TransactionAdded" | "TransactionEncryptionToggled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTransaction",
    values: [BigNumberish, string, BytesLike, BytesLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedMonthlyExpense",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedMonthlyIncome",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedMonthlyExpense",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedMonthlyIncome",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTransactionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTransactions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYearMonth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userTransactionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTransactions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedMonthlyExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedMonthlyIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedMonthlyExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedMonthlyIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYearMonth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTransactions",
    data: BytesLike
  ): Result;
}

export namespace TransactionAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    transactionId: BigNumberish,
    transactionType: BigNumberish,
    description: string,
    category: string,
    timestamp: BigNumberish,
    isEncrypted: boolean
  ];
  export type OutputTuple = [
    user: string,
    transactionId: bigint,
    transactionType: bigint,
    description: string,
    category: string,
    timestamp: bigint,
    isEncrypted: boolean
  ];
  export interface OutputObject {
    user: string;
    transactionId: bigint;
    transactionType: bigint;
    description: string;
    category: string;
    timestamp: bigint;
    isEncrypted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionEncryptionToggledEvent {
  export type InputTuple = [
    user: AddressLike,
    transactionId: BigNumberish,
    isEncrypted: boolean
  ];
  export type OutputTuple = [
    user: string,
    transactionId: bigint,
    isEncrypted: boolean
  ];
  export interface OutputObject {
    user: string;
    transactionId: bigint;
    isEncrypted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FinanceGuard extends BaseContract {
  connect(runner?: ContractRunner | null): FinanceGuard;
  waitForDeployment(): Promise<this>;

  interface: FinanceGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTransaction: TypedContractMethod<
    [
      transactionType: BigNumberish,
      description: string,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      category: string,
      encryptOnChain: boolean
    ],
    [void],
    "nonpayable"
  >;

  encryptedMonthlyExpense: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  encryptedMonthlyIncome: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedMonthlyExpense: TypedContractMethod<
    [user: AddressLike, yearMonth: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedMonthlyIncome: TypedContractMethod<
    [user: AddressLike, yearMonth: BigNumberish],
    [string],
    "view"
  >;

  getTransaction: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [FinanceGuard.TransactionStructOutput],
    "view"
  >;

  getUserTransactionCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserTransactions: TypedContractMethod<
    [user: AddressLike],
    [FinanceGuard.TransactionStructOutput[]],
    "view"
  >;

  getYearMonth: TypedContractMethod<
    [timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  userTransactionCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  userTransactions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, string, string, string, bigint, boolean] & {
        id: bigint;
        user: string;
        transactionType: bigint;
        description: string;
        encryptedAmount: string;
        category: string;
        timestamp: bigint;
        isEncrypted: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTransaction"
  ): TypedContractMethod<
    [
      transactionType: BigNumberish,
      description: string,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      category: string,
      encryptOnChain: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptedMonthlyExpense"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "encryptedMonthlyIncome"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedMonthlyExpense"
  ): TypedContractMethod<
    [user: AddressLike, yearMonth: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedMonthlyIncome"
  ): TypedContractMethod<
    [user: AddressLike, yearMonth: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [FinanceGuard.TransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTransactionCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTransactions"
  ): TypedContractMethod<
    [user: AddressLike],
    [FinanceGuard.TransactionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYearMonth"
  ): TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTransactionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTransactions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, string, string, string, bigint, boolean] & {
        id: bigint;
        user: string;
        transactionType: bigint;
        description: string;
        encryptedAmount: string;
        category: string;
        timestamp: bigint;
        isEncrypted: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TransactionAdded"
  ): TypedContractEvent<
    TransactionAddedEvent.InputTuple,
    TransactionAddedEvent.OutputTuple,
    TransactionAddedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionEncryptionToggled"
  ): TypedContractEvent<
    TransactionEncryptionToggledEvent.InputTuple,
    TransactionEncryptionToggledEvent.OutputTuple,
    TransactionEncryptionToggledEvent.OutputObject
  >;

  filters: {
    "TransactionAdded(address,uint256,uint8,string,string,uint256,bool)": TypedContractEvent<
      TransactionAddedEvent.InputTuple,
      TransactionAddedEvent.OutputTuple,
      TransactionAddedEvent.OutputObject
    >;
    TransactionAdded: TypedContractEvent<
      TransactionAddedEvent.InputTuple,
      TransactionAddedEvent.OutputTuple,
      TransactionAddedEvent.OutputObject
    >;

    "TransactionEncryptionToggled(address,uint256,bool)": TypedContractEvent<
      TransactionEncryptionToggledEvent.InputTuple,
      TransactionEncryptionToggledEvent.OutputTuple,
      TransactionEncryptionToggledEvent.OutputObject
    >;
    TransactionEncryptionToggled: TypedContractEvent<
      TransactionEncryptionToggledEvent.InputTuple,
      TransactionEncryptionToggledEvent.OutputTuple,
      TransactionEncryptionToggledEvent.OutputObject
    >;
  };
}
